### ISSUE TITLE
Usage without going through the fastify instance

### ISSUE THREAD

**Issue by zanechua** [jarcodallo/fastify-objectionjs#29]
There isn't any docs with regards about the usage without going through the `fastify` instance. 

It is actually possible to just use the model files directly while using this plugin to do the setup.

I supposed this was the intention for the plugin? Should we perhaps document this somewhere? 

```javascript
const UserModel = require('../Models/User');

const userData = await UserModel.query().findById(1);
```

**Comment by jarcodallo** [comment]
Yeah, sure thanks for the feedback.
