### ISSUE TITLE
Support for knexSnakeCaseMappers

### ISSUE THREAD

**Issue by zanechua** [jarcodallo/fastify-objectionjs#31]
This plugin is missing the support for `knexSnakeCaseMappers`. 

I'll see if I have some time to make a PR for this.

Docs: https://vincit.github.io/objection.js/api/objection/#knexsnakecasemappers

**Comment by kamikazechaser** [comment]
[fastify-objectionjs-classes](https://github.com/kamikazechaser/fastify-objectionjs-classes) can complement this plugin.

**Comment by jarcodallo** [comment]
I'll do this @zanechua thanks.
