### ISSUE TITLE
Add support of Fastify v3

### ISSUE THREAD

**Issue by GerardKetuma** [jarcodallo/fastify-objectionjs#38]
With the release of fastify v3, the fastify-plugin which is a dependency on this project needs to be updated to the v2.x series which support fastify v3.
See link to the fastify-plugin project below:
https://github.com/fastify/fastify-plugin

**Comment by jarcodallo** [comment]
I will

**Comment by jarcodallo** [comment]
Hi @GerardKetuma it was fixed on #43
