### ISSUE TITLE
Error when no jsonSchema provided

### ISSUE THREAD

**Issue by felixcatto** [jarcodallo/fastify-objectionjs#40]
Hi, in objection model `tableName` is the only required property. But your plugin also want `jsonSchema` and throws 'The supplied models are invalid.' error, if i don't provide it.

https://github.com/jarcodallo/fastify-objectionjs/blob/master/plugin.js#L53

**Comment by jarcodallo** [comment]
Thank you for you feedback, I'll add a validation for this.

**Comment by jarcodallo** [comment]
Hi @felixcatto it was fixed on #43
